name: Update Proxy List

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and update proxies
        run: |
          curl -s https://proxylist.geonode.com/api/proxy-list?page=1&limit=500&sort_by=responseTime&sort_type=asc | jq -r '.data[] | "\(.ip):\(.port)"' > all.txt
          curl -s "https://proxy-daily.com/api/export_proxies_ip_port?protocol=https" >> all.txt
          curl -s "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/http/data.txt" >> all.txt
          curl -s "https://proxy.webshare.io/api/v2/proxy/list/download/elemhvsjndkyaynxccapmgssiksxvwfqunvzjzro/-/any/username/direct/-/?plan_id=14393932" >> all.txt
          sort -u all.txt -o all.txt

      - name: Upload proxy artifact
        uses: actions/upload-artifact@v3
        with:
          name: proxy-list
          path: all.txt
